blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :blogs

  resources :user
  root 'blogs#index'
end

blog/app/models/post.rb
class Post < ApplicationRecord
end

blog/app/models/user.rb
class User < ApplicationRecord
  def new
  end

  def create
    @user = User.new(post_params)
  end

  private
    def post_params
      params.require(:user).permit(:fullname, :username, :password)
    end
end

blog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to :root
    else
      render 'new'
    end
  end

  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to :root
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to blogs_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :category, :content)
    end
end

blog/app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @user = User.all
  end

  def create
    p params[:username]
  end

  private
    def post_params
      params.require(:user).permit(:fullname, :username, :password)
    end
end

blog/app/helpers/blogs_helper.rb
module BlogsHelper
end

blog/app/helpers/user_helper.rb
module UserHelper
end

blog/app/views/blogs/_form_blog.html.erb
<%= form_for @post do |form| %>
<p>
    <%= form.label :title %>
    <%= form.text_field :title %>
</p>

<p>
    <%= form.label :category %>
    <%= form.text_field :category %>
</p>

<p>
    <%= form.label :content %>
    <%= form.text_area :content %>
</p>
<p>
    <%= form.submit %>
</p>
<% end %>

blog/app/views/blogs/edit.html.erb
<% @page_title = 'Edit' %>
<h2>Edit</h2>
<%= form_for @post, url: blog_path(@post) do |form| %>
<p>
    <%= form.label :title %>
    <%= form.text_field :title %>
</p>

<p>
    <%= form.label :category %>
    <%= form.text_field :category %>
</p>

<p>
    <%= form.label :content %>
    <%= form.text_area :content %>
</p>
<p>
    <%= form.submit %>
</p>
<% end %>

blog/app/views/blogs/index.html.erb
<% @page_title = 'Index' %>
<h1>Show blog</h1>
<table>
    <tr>
        <th>Title</th>
        <th>*<th>
    </tr>
    <% @post.each do |p| %>
    <tr>
        <td><%= p.title %></td>
        <td>
            <%= link_to 'Show', blog_path(p) %>
            <%= link_to 'Edit', edit_blog_path(p) %>
            <%= link_to 'Delete', blog_path(p), method: :delete %>
        </td>
    </tr>
    <% end %>
</table>

blog/app/views/blogs/new.html.erb
<% @page_title = 'New blog' %>
<h1>New blog</h1>
<%= render 'form_blog' %>

blog/app/views/blogs/show.html.erb
<% @page_title = 'Show' %>
<h2>Show</h2>
<p>Title: <%= @post.title %></p>
<p>Category: <%= @post.category %></p>
<p>Content: <%= @post.content %></p>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/user/new.html.erb
<% @page_title = 'Register' %>
<h2>Register</h2>
<%= form_for @user, url: user_index_path do |f| %>
<p>
    Fullname:
    <%= f.text_field :fullname %>
</p>

<p>
    Username:
    <%= f.text_field :username %>
</p>

<p>
    Password:
    <%= f.password_field :password %>
</p>

<p>
    <%= f.submit %>
</p>
<% end %>